### PR TITLE
Don't commit commented code.

### PR DESCRIPTION
**Pull request by steveklabnik**
That's what git is for.

### CODE REVIEW

**Comment by sendtodns** [comment]
Removed commented code!

**Comment by steveklabnik** [comment]
Woo!

I noticed that you made new commits rather than merging mine in; was that on purpose or an accident? I'm just curious.

**Comment by sendtodns** [comment]
On Saturday, February 25, 2012, Steve Klabnik wrote:

> Woo!
> 
> I noticed that you made new commits rather than merging mine in; was that
> on purpose or an accident? I'm just curious.

After the first change it said your branches couldn't be merged.  I'm still
getting used to the git workflow for handling pull requests, so anything
I'm messing up let me know. Thanks for your help so far.

## 

Kyle Sexton

**Comment by steveklabnik** [comment]
Ahhh yes. This happens.

The easiest thing to do when this occurs is to leave a message on the pull request asking them to rebase their changes. It shouldn't be your job as a maintainer to fix conflicts, that's the job of the pull requester. Alternatively, if you're feeling generous, you can do a git merge yourself and fix the conflicts.

There are two big problems with what you did: #1, you have to manually re-create my changes. Lots of work for you. My requests weren't that large, but others in the future might be. Secondly, the commit is attributed to you, not me, so if someone has a question, they'll ask you about it. ;) And I don't get credit.

This doesn't mean you should go back and re-do this for the things I changed, but keep it in mind for the future. :)

**Comment by sendtodns** [comment]
On Saturday, February 25, 2012, Steve Klabnik wrote:

> Ahhh yes. This happens.
> 
> The easiest thing to do when this occurs is to leave a message on the pull
> request asking them to rebase their changes. It shouldn't be your job as a
> maintainer to fix conflicts, that's the job of the pull requester.
> Alternatively, if you're feeling generous, you can do a git merge yourself
> and fix the conflicts.
> 
> There are two big problems with what you did: #1, you have to manually
> re-create my changes. Lots of work for you. My requests weren't that large,
> but others in the future might be. Secondly, the commit is attributed to
> you, not me, so if someone has a question, they'll ask you about it. ;) And
> I don't get credit.

Ahhh, that makes sense.  That must be why the first change I did
automatically closed the pull request.

## 

Kyle Sexton

**Comment by steveklabnik** [comment]
Yep! If you manually do it, it knows that commit was attached to a pull request, and closes it for you.

If you have an Issue that you're fixing with a commit, you can add "Fixes #3" or whatever in the commit message, and it'll automatically close the pull request, and link to the commit, which is cool.

Okay, so as an example, see how my 'gemify' pull request won't merge? I'm going to go rebase it now and push my changes. If you check it afterward, it should say you can automatically merge.

**Pull request closed without merging**
